kind: ConfigMap
apiVersion: v1
metadata:
  name: managed-service-operators.v0.0.1
  namespace: kube-system

data:
  customResourceDefinitions: |-
    - apiVersion: apiextensions.k8s.io/v1beta1
      kind: CustomResourceDefinition
      metadata:
        name: integrations.integreatly.org
      spec:
        group: integreatly.org
        names:
          kind: Integration
          listKind: IntegrationList
          plural: integrations
          singular: integration
        scope: Namespaced
        version: v1alpha1
        validation:
          openAPIV3Schema:
            properties:
              spec:
                properties:
                  serviceProvider:
                    type: string
                  integrationType:
                    type: string
                  client:
                    type: string
                  enabled:
                    type: boolean
                  metaData:
                    type: object

  clusterServiceVersions: |-
    - apiVersion: operators.coreos.com/v1alpha1
      kind: ClusterServiceVersion
      metadata:
        name: integration-controller-0.0.1
        namespace: managed-service-broker
      spec:
        displayName: Integration Controller
        description: |
              Knows how to enable various integrations between certain sets of products.
        version: 1.0.0-beta
        maturity: beta
        maintainers:
        - name: Integreatly, Inc.
          email: customerservice@redhat.com
        provider:
          name: Integreatly, Inc.
        install:
          strategy: deployment
          spec:
            permissions:
            - serviceAccountName: syndesis-operator
              rules:
              - apiGroups:
                - integreatly.org
                resources:
                - "*"
                verbs:
                - "*"
            deployments:
            - name: integration-controller
              spec:
                replicas: 1
                selector:
                  matchLabels:
                    name: integration-controller
                template:
                  metadata:
                    labels:
                      name: integration-controller
                  spec:
                    restartPolicy: Always
                    terminationGracePeriodSeconds: 5
                    serviceAccountName: integration-controller
                    serviceAccount: integration-controller
                    containers:
                    - name: integration-controller
                      image: quay.io/integreatly/integration-controller:dev
                      - containerPort: 60000
                      name: metrics
                      command:
                      - integration-controller
                      - --allow-insecure=true
                      - --log-level=debug
                      imagePullPolicy: Always
                      env:
                        - name: WATCH_NAMESPACE
                          valueFrom:
                            fieldRef:
                              fieldPath: metadata.namespace
                        - name: POD_NAME
                          valueFrom:
                            fieldRef:
                              fieldPath: metadata.name
                        - name: OPERATOR_NAME
                          value: "integration-controller"
        customresourcedefinitions:
          owned:
          - name: integrations.integreatly.org
            version: v1alpha1
            kind: Integration
            displayName: Integration
            description: Represents an instance of an Integration between 2 services.

  packages: |-
    - packageName: integration-controller
      channels:
      - name: poc
        currentCSV: integration-controller-0.0.1
