apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: syndesises.syndesis.io
spec:
  group: syndesis.io
  version: v1alpha1
  names:
    kind: Syndesis
    listKind: SyndesisList
    plural: syndesises
    singular: syndesis
  scope: Namespaced
