kind: ConfigMap
apiVersion: v1
metadata:
  name: managed-service-operators.v0.0.1
  namespace: kube-system

data:
  customResourceDefinitions: |-
    - apiVersion: apiextensions.k8s.io/v1beta1
      kind: CustomResourceDefinition
      metadata:
        name: syndesises.syndesis.io
      spec:
        group: syndesis.io
        version: v1alpha1
        names:
          kind: Syndesis
          listKind: SyndesisList
          plural: syndesises
          singular: syndesis
        scope: Namespaced

  clusterServiceVersions: |-
    - apiVersion: operators.coreos.com/v1alpha1
      kind: ClusterServiceVersion
      metadata:
        name: syndesis-0.0.1
        namespace: operator-lifecycle-manager
      spec:
        displayName: Syndesis Infrastructure Operator
        description: |
              A flexible, customizable, open source platform that provides core integration capabilities as a service.
        version: 1.0.0-beta
        maturity: beta
        maintainers:
        - name: Integreatly, Inc.
          email: customerservice@redhat.com
        provider:
          name: Integreatly, Inc.
        install:
          strategy: deployment
          spec:
            permissions:
            - serviceAccountName: syndesis-operator
              rules:
              - apiGroups:
                - "*"
                resources:
                - "*"
                verbs:
                - "*"
            deployments:
            - name: syndesis-operator
              spec:
                replicas: 1
                selector:
                  matchLabels:
                    app: syndesis
                template:
                  metadata:
                    labels:
                      app: syndesis
                  spec:
                    restartPolicy: Always
                    terminationGracePeriodSeconds: 5
                    serviceAccountName: syndesis-operator
                    serviceAccount: syndesis-operator
                    containers:
                    - name: syndesis-operator
                      image: docker.io/syndesis/syndesis-operator:latest
                      env:
                        - name: WATCH_NAMESPACE
                          valueFrom:
                            fieldRef:
                              fieldPath: metadata.namespace
                        - name: POD_NAME
                          valueFrom:
                            fieldRef:
                              fieldPath: metadata.name
                        - name: OPERATOR_NAME
                          value: "syndesis-operator"
        customresourcedefinitions:
          owned:
          - name: syndesises.syndesis.io
            version: v1alpha1
            kind: Syndesis
            displayName: Syndesis
            description: Represents an instance of a Syndesis application

  packages: |-
    - packageName: syndesis-operator
      channels:
      - name: poc
        currentCSV: syndesis-0.0.1
