apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  labels:
    app: syndesis
    syndesis.io/app: syndesis
    syndesis.io/type: operator
    syndesis.io/component: syndesis-operator
  name: fuse-online-operator
spec:
  lookupPolicy:
    local: false
  tags:
  - from:
      kind: DockerImage
      name: registry.access.redhat.com/fuse7/fuse-online-operator:1.1-6
    importPolicy:
      scheduled: true
    name: "1.4"