kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: managed-service-controller
rules:
- apiGroups:
  - integreatly.org
  resources:
  - managedservicenamespaces
  verbs:
  - "*"
---

kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  generateName: default-account-managed-service-controller-
  labels:
    for: managed-service-controller
subjects:
- kind: ServiceAccount
  name: default
  namespace: ${NAMESPACE}
roleRef:
  kind: Role
  name: managed-service-controller
  apiGroup: rbac.authorization.k8s.io

---

kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: managed-service-controller-admin
rules:
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - create
  - delete
  - get
  - list
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - rolebindings
  verbs:
  - create
---

kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  generateName: managed-service-controller-admin-
  labels:
    for: managed-service-controller
roleRef:
  kind: ClusterRole
  name: managed-service-controller-admin
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: default
  namespace: ${NAMESPACE}
---

kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  generateName: managed-service-controller-view-
  labels:
    for: managed-service-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: view
subjects:
- kind: ServiceAccount
  name: default
  namespace: ${NAMESPACE}