---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  generateName: managed-service-controller-sa-
  labels:
    for: managed-service-controller
subjects:
- kind: ServiceAccount
  name: managed-service-controller
  namespace: {NAMESPACE}
roleRef:
  kind: Role
  name: managed-service-controller
  apiGroup: rbac.authorization.k8s.io

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  generateName: managed-service-controller-admin-
  labels:
    for: managed-service-controller
roleRef:
  kind: ClusterRole
  name: managed-service-controller-admin
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: managed-service-controller
  namespace: {NAMESPACE}

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  generateName: managed-service-controller-view-
  labels:
    for: managed-service-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: view
subjects:
- kind: ServiceAccount
  name: managed-service-controller
  namespace: {NAMESPACE}