---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: managed-service-controller
rules:
- apiGroups:
  - integreatly.org
  resources:
  - managedservicenamespaces
  verbs:
  - "*"

---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  creationTimestamp: null
  name: managed-service-controller-admin
rules:
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - create
  - delete
  - get
  - list
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - rolebindings
  verbs:
  - create
- apiGroups:
  - user.openshift.io
  resources:
  - users
  verbs:
  - get